### ISSUE TITLE
TODO tracker

### ISSUE THREAD

**Issue by fsantini** [dafne-imaging/dafne-server#1]
Todo list for the server
- [x] Support for multiple models (identified by string ('thigh', 'leg', etc)?)
- [x] Model repository with history
- [x] API call to obtain latest timestamp (hash?) of model
- [x] Store multiple models (improvement of the same baseline model)
- [x] Log activities 
- [x] Federated learning
- [ ] Model validation (should it be done on the federated model or on each incremental model?)
- [ ] Model Delta compression (discard delta weights below threshold?)

Model download/upload concept:

1. Client sends a ModelInfo request to Server. Communicates username/password hash, desired model. Server replies with the timestamp (hash?) of the latest model
2. Decided by the client, the client retrieves the latest model with a ModelGet request. Communicates username/password hash and retrieves either: 
   - Delta model (if client communicates a baseline hash)
   - Full model (if client doesn't communicate a baseline hash)
3. After incremental learning, the client sends the model (or ideally, a compressed delta) to the server with a ModelPut. It communicates:
   - Username/password hash
   - Baseline of the original model
   - Dice score between originally automatically segmented maps and manually refined maps (for statistics)
4. The new model is stored while waiting for federation.
